export function About() {
    return (
        <div class="about" id="info">
            <div class="container">
                <div>
                    <h2 data-lang-en="Allow me to introduce myself" data-lang-es="Permíteme presentarme">Permíteme presentarme</h2>
                    <p data-lang-en="As a student in Computer Science, I've spent countless nights coding, debugging, and consuming unhealthy amounts of caffeine. One of my proudest moments was developing an application and databases for a local enterprise, which increased their efficiency by 70%. On my student path, I've been contributing in a lot of software projects based on business situations, helping me to improve my skills as a software developer." data-lang-es="Como estudiante de Ingenieria de sistemas, he pasado incontables noches programando, depurando y consumiendo cantidades poco saludables de cafeína. Uno de mis momentos más orgullosos fue desarrollar una aplicación y bases de datos para una empresa local, que aumentó su eficiencia en un 70%. En mi camino estudiantil, he estado contribuyendo en muchos proyectos de software basados en situaciones empresariales, ayudándome a mejorar mis habilidades como desarrollador de software.">Como estudiante de Ingenieria de sistemas, he pasado incontables noches programando, depurando y consumiendo cantidades poco saludables de cafeína. Uno de mis momentos más orgullosos fue desarrollar una aplicación y bases de datos para una empresa local, que aumentó su eficiencia en un 70%. En mi camino estudiantil, he estado contribuyendo en muchos proyectos de software basados en situaciones empresariales, ayudándome a mejorar mis habilidades como desarrollador de software.</p>
                </div>
                    <img class="sobremii" src="/public/images/sobremi.jpg" alt="about"/>
            </div>
            <div class="info">
                <div class="card" id="mision">
                    <img src="/public/images/icons/mision.png" alt="mision"/>
                    <div class="card__content">
                        <p class="card__title" data-lang-en="My Mission" data-lang-es="Mi Misión">Mi Misión</p>
                        <p class="card__description" data-lang-en="I am a software developer dedicated to creating technological solutions that optimize daily and work processes, saving time and costs while improving business efficiency. I focus on continuously innovating to keep my clients at the forefront of the market. My competitive advantage lies in understanding the client's needs and adding a distinctive touch to each program, always thinking of future improvements. I differentiate myself by my ability to solve demands, dedication to each project, and continuous support, ensuring the delivery of quality materials that are updated according to emerging needs." data-lang-es="Soy un desarrollador de software dedicado a crear soluciones tecnológicas que optimicen procesos diarios y laborales, ahorrando tiempo y costos mientras mejoran la eficiencia empresarial. Me enfoco en innovar continuamente para mantener a mis clientes a la vanguardia del mercado. Mi ventaja competitiva radica en comprender las necesidades del cliente y añadir un toque distintivo a cada programa, pensando siempre en mejoras futuras. Me diferencio por mi habilidad para resolver demandas, la dedicación a cada proyecto y el acompañamiento continuo, asegurando la entrega de materiales de calidad que se actualizan según las necesidades emergentes.">Soy un desarrollador de software dedicado a crear soluciones tecnológicas que optimicen procesos diarios y laborales, ahorrando tiempo y costos mientras mejoran la eficiencia empresarial. Me enfoco en innovar continuamente para mantener a mis clientes a la vanguardia del mercado. Mi ventaja competitiva radica en comprender las necesidades del cliente y añadir un toque distintivo a cada programa, pensando siempre en mejoras futuras. Me diferencio por mi habilidad para resolver demandas, la dedicación a cada proyecto y el acompañamiento continuo, asegurando la entrega de materiales de calidad que se actualizan según las necesidades emergentes.</p>
                    </div>
                </div>
                <div class="card" id="vision">
                    <img src="/public/images/icons/vision.png" alt="vision"/>
                    <div class="card__content">
                        <p class="card__title" data-lang-en="My Vision" data-lang-es="Mi Visión">Mi Visión</p>
                        <p class="card__description" data-lang-en="I aspire to be remembered for effectively resolving and meeting client demands, overcoming any challenge with confidence and determination. I specialize in time management and providing innovative solutions. My services are aimed at small and medium-sized enterprises that need systems to manage production, work, or finance, and web services. My goal is to excel as a programmer, gaining recognition and recommendation from my clients due to the high quality of my work. In the future, I want to be one of the best programmers and software developers, accumulating extensive knowledge and specializing in a specific environment." data-lang-es="Aspiro a ser recordado por resolver y satisfacer eficazmente las demandas de los clientes, superando cualquier desafío con confianza y determinación. Me especializo en gestionar el tiempo y proporcionar soluciones innovadoras. Mis servicios están dirigidos a pequeñas y medianas empresas que necesitan sistemas para gestionar producción, trabajo o finanzas, y servicios web. Mi meta es sobresalir como programador, obteniendo el reconocimiento y recomendación de mis clientes gracias a la alta calidad de mis trabajos. En el futuro, quiero ser uno de los mejores programadores y desarrolladores de software, acumulando conocimientos extensos y especializándome en un entorno específico.">Aspiro a ser recordado por resolver y satisfacer eficazmente las demandas de los clientes, superando cualquier desafío con confianza y determinación. Me especializo en gestionar el tiempo y proporcionar soluciones innovadoras. Mis servicios están dirigidos a pequeñas y medianas empresas que necesitan sistemas para gestionar producción, trabajo o finanzas, y servicios web. Mi meta es sobresalir como programador, obteniendo el reconocimiento y recomendación de mis clientes gracias a la alta calidad de mis trabajos. En el futuro, quiero ser uno de los mejores programadores y desarrolladores de software, acumulando conocimientos extensos y especializándome en un entorno específico.</p>
                    </div>
                </div>
            </div>
        </div>
    );
}